name: Deploy to Amazon ECR

on:
  push:
    branches:
      - aws_integration # Workflow hanya jalan jika ada push ke branch ini

env:
  AWS_REGION: ap-southeast-1 # Singapura
  ECR_REPOSITORY: sporton-frontend # Sesuaikan (frontend atau backend)
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  deploy:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode dari GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Konfigurasi Kredensial AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Login ke Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Build, Tag, dan Push Image ke ECR dengan Build Args
      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
          # Mengambil rahasia dari GitHub Secrets untuk dioper ke Docker
          API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=$API_URL \
            --build-arg NEXT_PUBLIC_API_URL_ROOT=$API_URL \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
